### ISSUE TITLE
status: 500, response: {"errors":[{"field":null,"message":"internal server error"}]}

### ISSUE THREAD

**Issue by smag-bmesseca** [Trois-Six/terraform-provider-sendgrid#10]
Until v0.1.6, we are unable to create new SendGRID api.

We got an error 500 : internal server error

```hcl
Error: request failed: failed creating apiKey, status: 500, response: {"errors":[{"field":null,"message":"internal server error"}]}
  on main.tf line 100, in resource "sendgrid_api_key" "main":
 100: resource "sendgrid_api_key" "main" {
```

We are using terraform 0.13.3 with following code : 

```hcl
provider "sendgrid" {
  api_key = "xxxxxxxx"
}
resource "sendgrid_api_key" "main" {
  name = "myApiName"
  scopes = [
    "mail.send",
  ]
}
```

It's working fine with curl commmand line : 

```shell
$ curl --request POST --url https://api.sendgrid.com/v3/api_keys --header 'authorization: Bearer SG.xxxxxxx.xxxxxxxx' --header 'content-type: application/json' --data '{"name":"myApiName","scopes":["mail.send"]}'
{"api_key":"SG.xxxxxxx.xxxxxxx","api_key_id":"xxxxxxx","name":"myApiName","scopes":["mail.send"]}
```

It was working fine on v0.1.3 but we are not able to use it anymore because of 404 error

```hcl
Error while installing trois-six/sendgrid v0.1.3: could not query provider
registry for registry.terraform.io/trois-six/sendgrid: failed to retrieve
authentication checksums for provider: 404 Not Found
```

Thanks in advance.

**Comment by Trois-Six** [comment]
Hello,
I am sorry I changed my job and I am not working with Sendgrid anymore.
Pierre

**Comment by smag-bmesseca** [comment]
Ok thanks for the quick answer.

I think I found the problem. This is due to the presence of the scope: sender_verification_eligible in the provider
If I remove it from the provider source, the API key is created fine.

If you no longer support the provider, I will probably fork in the terraform registry.
What do you think ?

**Comment by Trois-Six** [comment]
yes please do it. I will put this repository in read-only mode.
