### ISSUE TITLE
Domain Authentication resources

### ISSUE THREAD

**Issue by timja** [Trois-Six/terraform-provider-sendgrid#8]
sendgrid_domain_authentication
sendgrid_domain_authentication_validation

Suggested schema:

```hcl
resource "sendgrid_domain_authentication" "domain" {
  domain                = "example.com"
  sub_user_on_behalf_of = "my_sub_user" # optional
  subdomain             = "sub"      # optional
  username              = "username" # optional
  ips                   = []         # optional
  custom_spf            = false      # optional
  default               = false      # optional
  automatic_security    = true       # optional
  custom_dkim_selector  = ""         # optional
}

resource "sendgrid_domain_authentication_validation" "domain" {
  id = sendgrid_domain_authentication.domain.id
  sub_user_on_behalf_of = "my_sub_user" # optional
}
```

after the `sendgrid_domain_authentication` is complete then you would be able to use another terraform resource to create the required DNS validation records, `sendgrid_domain_authentication_validation` needs to poll for some reasonable time to see if sendgrid validates the domain.

API docs:
https://sendgrid.com/docs/api-reference/

Actions are:

1. Authenticate a domain
1. Validate a domain authentication.

@Trois-Six any thoughts?

**Comment by Trois-Six** [comment]
yes great! I am so sorry I can't help you but PRs are welcome as usual.

**Comment by zsozso** [comment]
I have problem which is probably related with _sendgrid_domain_authentication_  resource.
Whenever I execute Terraform it is always creating a new Cname records independently from the sendgrid resource was already created
Is it a bug or you have an idea how I can avoid the regeneration?

```
resource "sendgrid_domain_authentication" "default" {
  domain = "${var.dns_zone_name}"
  is_default = true
  automatic_security = true
}

resource "azurerm_dns_cname_record" "sendgrid" {
  depends_on = [
     sendgrid_domain_authentication.default
  ]
  count = 3 // SendGrid generates 3 different CNAME records

  name = trimsuffix(sendgrid_domain_authentication.default.dns[count.index].host, ".${var.dns_zone_name}")
  resource_group_name = "${data.azurerm_dns_zone.dns_zone.resource_group_name}"
  zone_name           = "${data.azurerm_dns_zone.dns_zone.name}"
  ttl                 = 3600
  record =  "${sendgrid_domain_authentication.default.dns[count.index].data}"
}
```
Thank you

**Comment by timja** [comment]
This issue was about the creation of the resource which appears to have been done.

You should probably create a new issue for your thing
